trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11.5'
    addToPath: true

- script: python -m pip install --upgrade pip
  displayName: 'Install pip'

- script: pip install -r requirements.txt
  displayName: 'Install requirements'

- script: python manage.py test
  displayName: 'Run tests'